# 無効にするルール
disabled_rules:
- force_cast
- force_try

# デフォルトルール以外でopt-inから適用させるルールの設定
opt_in_rules:

# SwiftLintの適用から外すディレクトリ
excluded:
- Pods/
- Carthage/
- RandomChoiceTests/

# 1行あたりの文字数制限を300に変更
line_length: 300
